/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "black": "var(--color-on-background)",
        "white": "var(--color-surface)",
        "tertiary": "var(--color-tertiary)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary": "var(--color-primary)",
        "on-background": "var(--color-on-background)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-container-low": "var(--color-surface-container-low)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface": "var(--color-surface)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "outline": "var(--color-outline)",
        "on-primary-container": "var(--color-on-primary-container)",
        "error-container": "var(--color-error-container)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "on-surface": "var(--color-on-surface)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary": "var(--color-secondary)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "background": "var(--color-background)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "error": "var(--color-error)",
        "surface-variant": "var(--color-surface-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "on-error": "var(--color-on-error)",
        "on-surface-variant": "var(--color-on-surface-variant)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap": "120px",
        "stack-lg": "48px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        display: ["Bricolage Grotesque", "sans-serif"],
        body: ["Geist", "sans-serif"],
        accent: ["Sora", "sans-serif"],
        "display-lg-mobile": ["Bricolage Grotesque", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Bricolage Grotesque", "sans-serif"],
        "headline-lg": ["Bricolage Grotesque", "sans-serif"],
        "headline-md": ["Bricolage Grotesque", "sans-serif"],
        "display-lg": ["Bricolage Grotesque", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-sm": ["Sora", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
