# Generated by Django 6.0.7 on 2026-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('lien', models.URLField(blank=True)),
            ],
        ),
    ]
