# Generated by Django 6.1 on 2026-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='snippet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
