# Generated by Django 6.1 on 2026-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated skills (e.g. React, Node.js)', max_length=255),
        ),
    ]
