# Generated by Django 6.0.6 on 2026-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.PositiveIntegerField(blank=True, help_text="ID de l'événement associé (optionnel)", null=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
