# Generated by Django 6.0.6 on 2026-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('pdf', 'PDF'), ('support_cours', 'Support de cours'), ('tutoriel', 'Tutoriel'), ('presentation', 'Présentation'), ('lien_utile', 'Lien utile')], default='pdf', max_length=30)),
                ('fichier_url', models.URLField(blank=True, max_length=500)),
                ('evenement', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
